# Generated by Django 3.2.5 on 2021-08-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('userBigCity', models.CharField(max_length=10)),
                ('userSmallCity', models.CharField(max_length=10)),
                ('userDetailCity', models.CharField(max_length=10)),
                ('lookupCount', models.IntegerField()),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
