# Generated by Django 3.2.5 on 2021-08-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyboard',
            name='gatherMember',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='studyboard',
            name='lookupCount',
            field=models.IntegerField(default=0),
        ),
    ]
