# Generated by Django 3.2.5 on 2021-08-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210807_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyboard',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studyboard',
            name='userDetailCity',
            field=models.CharField(max_length=100),
        ),
    ]
