# Generated by Django 3.2.5 on 2021-08-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210808_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='getUsernameByToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('mytoken', models.CharField(max_length=50)),
            ],
        ),
    ]
