# Generated by Django 3.2.5 on 2021-08-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_getusernamebytoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='getUsernameByToken',
        ),
    ]
