# Generated by Django 3.2.5 on 2021-08-09 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_delete_getusernamebytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyboard',
            name='userkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_user', models.TextField(max_length=20)),
                ('comment_textfield', models.TextField()),
                ('studyboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.studyboard')),
            ],
        ),
    ]
