# Generated by Django 3.2.5 on 2021-08-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_studyboard_userkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='studyboard',
            new_name='comment_key',
        ),
    ]
