# Generated by Django 3.2.5 on 2021-08-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_studyboard_comment_comment_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_key',
            new_name='studyboard',
        ),
    ]
